select
    DESCRIPTION,
    FILTER_LEVEL_2 as CATEGORY,
    FILTER_LEVEL_3 as STOCK_NAME,
    BENCHMARK_WEIGHT,
    ACTIVE_WEIGHT,
    PORTFOLIO_RETURN,
    BENCHMARK_RETURN,
    ACTIVE_RETURN,
    PORTFOLIO_RETURNCONTRIBUTION,
    BENCHMARK_RETURNCONTRIBUTION,
    ACTIVE_RETURNCONTRIBUTION,
    SECTOR_ALLOCATION


from {{source('raw_data','ACTIVE_ATTRIBUTION_TABLE')}}