select
    
    NNIP_ENVIRONMENT_SCORE,
    NNIP_GOVERNANCE_SCORE,
    NNIP_SOCIAL_SCORE,
    HIGHEST_CONTROVERSY_LEVEL_ANSWER_CATEGORY AS CONTROVERSIAL_CATEGORY,
    SUSTAINALYTICS_TOTAL_EXPOSURE_SCORE,
    SUSTAINALYTICS_GOVERNANCE_SCORE,
    SUSTAINALYTICS_ENVIRONMENT_SCORE,
    SUSTAINALYTICS_SOCIAL_SCORE,
    SUSTAINALYTICS_GOVERNANCE_RISK_SCORE,
    SUSTAINALYTICS_SOCIAL_RISK_SCORE,
    SUSTAINALYTICS_MANAGED_RISK_SCORE,
    SUSTAINALYTICS_MANAGEABLE_RISK_SCORE,
    SUSTAINALYTICS_UNMANAGEABLE_RISKS_SCORE,
    SUSTAINALYTICS_UNMANAGED_RISK_SCORE,
    CO2_EMISSIONS_SCOPE_1_2_3_INTENSITY AS CO2_EMISSIONS_INTENSITY,
    WASTE_PRODUCED_INTENSITY,
    WATER_CONSUMED_INTENSITY,
    SUSTAINALYTICS_MANAGEMENT_GAP_SCORE

from {{source('raw_data','ANALYTICS_TABLE')}}