aesg_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <"account_name">

      # User/password auth
      user: "user_name"
      password: "password"
      role: ACCOUNTADMIN
      database: ESG_database
      warehouse: d2b_warehouse
      schema: ESG_schema
      threads: 1 
      client_session_keep_alive: False
      query_tag: dbt-snowflake
